objects/Page_Question__c.object
<CustomObject>
    <fields>
        <fullName>Page_Text__c</fullName>
        <label>Page Text</label>
        <referenceTo>Page_Text__c</referenceTo>
        <relationshipLabel>Page Question</relationshipLabel>
        <relationshipName>Page_Question</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subsection__c</fullName>
        <label>Subsection</label>
        <picklist>
            <picklistValues>
                <fullName>1.1 Vision and approach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.2 Scope of the report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.1 The social problem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.1a Problem Causes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.1b Consequences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.1c Target Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.2 Solution attempts made to date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.3 The solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.1 Resources used (input)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.2 Work performed (output)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.3 Results achieved (outcome/impact)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.4 Presenting resources, work performed and results during the reporting period</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.5 Provisions taken for the accompanying evaluation and qualitiy assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.6 Previous year comparison: Objectives achieved, learning experience and success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.1 Planning and targets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.2 Influence factors: chances and risks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.1 Organisational structure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.2 Introduction of the participating individuals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.3 Partnerships, cooperations and networks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.1 General information about the organisation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.2 Governance of the organisation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.3 Ownership structure, memberships and associated organisations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.4 Environmental and social profile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7.1 Bookkeeping and accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7.2 Asset statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7.3 Income and expenditure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7.4 Financial situation and planning</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Page Question</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Page Questions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Question</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Page_Text__c.object
<CustomObject>
    <label>Page Text</label>
    <nameField>
        <label>Page Text Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Page Text</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestPostInstall.cls
@IsTest
public class TestPostInstall
{
@isTest
static void testInstallScript() {
  PostInstallClass postinstall = new PostInstallClass();
    Test.testInstall(postinstall, null);
    Test.testInstall(postinstall, new Version(1,0), true);
    List<Page_Text__c> lstPgText = [Select id, name from Page_Text__c];

    List<Page_Question__c> lstPgQuestion = [Select id, Page_Text__c, Subsection__c from Page_Question__c];
    System.debug(lstPgQuestion);

    System.assert((lstPgText.size() > 0) && (lstPgQuestion.size() > 0));
  }
}